// a1.config.js - Menschen A1 Vocabulary
const RAW_A1_DATA = [
    "1|e|Hallo!|Hello!|Hallo, ich bin Anna.|Hello, I am Anna.",
    "1|e|Guten Morgen!|Good morning!|Guten Morgen, Frau Müller!|Good morning, Mrs. Müller!",
    "1|e|Guten Tag!|Good day!|Guten Tag, wie geht es Ihnen?|Good day, how are you?",
    "1|e|Guten Abend!|Good evening!|Guten Abend, Herr Schmidt.|Good evening, Mr. Schmidt.",
    "1|e|Gute Nacht!|Good night!|Gute Nacht, schlaf gut!|Good night, sleep well!",
    "1|e|Auf Wiedersehen!|Goodbye!|Auf Wiedersehen, bis morgen!|Goodbye, see you tomorrow!",
    "1|e|Tschüs!|Bye!|Tschüs, bis bald!|Bye, see you soon!",
    "1|e|Wie geht es Ihnen?|How are you? (formal)|Wie geht es Ihnen heute?|How are you today?",
    "1|e|Wie geht's?|How are you? (informal)|Hallo, wie geht's?|Hello, how are you?",
    "1|e|Danke, gut.|Thanks, fine.|Wie geht's? – Danke, gut.|How are you? – Thanks, fine.",
    "1|e|Sehr gut!|Very good!|Mir geht es sehr gut!|I am very good!",
    "1|e|Es geht.|So-so.|Wie geht's? – Es geht.|How are you? – So-so.",
    "1|e|Nicht so gut.|Not so good.|Mir geht es nicht so gut.|I am not so good.",
    "1|e|Danke!|Thank you!|Danke, das ist nett!|Thank you, that is nice!",
    "1|e|Bitte!|Please! / You're welcome!|Bitte, hier ist der Kaffee.|Here you go, here is the coffee.",
    "1|e|Entschuldigung!|Excuse me! / Sorry!|Entschuldigung, wie heißen Sie?|Excuse me, what is your name?",
    "1|v|heißen|to be called|Ich heiße Maria.|My name is Maria.",
    "1|v|sein (ist)|to be|Er ist aus Deutschland.|He is from Germany.",
    "1|v|kommen|to come|Ich komme aus der Türkei.|I come from Turkey.",
    "1|v|gehen (geht)|to go|Wie geht es dir?|How are you?",
    "1|p|ich|I|Ich bin Studentin.|I am a student.",
    "1|p|du|you (informal)|Wie heißt du?|What is your name?",
    "1|p|Sie|you (formal)|Woher kommen Sie?|Where do you come from?",
    "1|n|der Name, -n|the name|Mein Name ist Thomas.|My name is Thomas.",
    "1|n|die Frau, -en|the woman / Mrs.|Die Frau heißt Sabine.|The woman is called Sabine.",
    "1|n|der Herr, -en|the gentleman / Mr.|Der Herr kommt aus Wien.|The gentleman comes from Vienna.",
    "1|a|gut|good|Das ist gut.|That is good.",
    "1|a|schlecht|bad|Das Wetter ist schlecht.|The weather is bad.",
    "1|d|auch|also|Ich bin auch aus Berlin.|I am also from Berlin.",
    "1|d|sehr|very|Sehr gut, danke!|Very good, thank you!",
    "2|n|der Beruf, -e|the profession|Was ist Ihr Beruf?|What is your profession?",
    "2|n|der Lehrer, -|the teacher (m)|Der Lehrer ist sehr nett.|The teacher is very nice.",
    "2|n|die Lehrerin, -nen|the teacher (f)|Die Lehrerin kommt aus Hamburg.|The teacher comes from Hamburg.",
    "2|n|der Arzt, -¨e|the doctor (m)|Der Arzt arbeitet im Krankenhaus.|The doctor works in the hospital.",
    "2|n|die Ärztin, -nen|the doctor (f)|Die Ärztin ist sehr freundlich.|The doctor is very friendly.",
    "2|n|der Student, -en|the student (m)|Der Student lernt Deutsch.|The student is learning German.",
    "2|n|die Studentin, -nen|the student (f)|Die Studentin kommt aus Brasilien.|The student comes from Brazil.",
    "2|n|der Ingenieur, -e|the engineer (m)|Mein Vater ist Ingenieur.|My father is an engineer.",
    "2|n|die Ingenieurin, -nen|the engineer (f)|Die Ingenieurin arbeitet bei Siemens.|The engineer works at Siemens.",
    "2|n|der Kellner, -|the waiter|Der Kellner bringt das Essen.|The waiter brings the food.",
    "2|n|die Kellnerin, -nen|the waitress|Die Kellnerin ist sehr schnell.|The waitress is very fast.",
    "2|n|der Verkäufer, -|the salesperson (m)|Der Verkäufer arbeitet im Supermarkt.|The salesperson works in the supermarket.",
    "2|n|die Verkäuferin, -nen|the salesperson (f)|Die Verkäuferin ist freundlich.|The salesperson is friendly.",
    "2|n|der Journalist, -en|the journalist (m)|Der Journalist schreibt einen Artikel.|The journalist writes an article.",
    "2|n|der Programmierer, -|the programmer (m)|Der Programmierer arbeitet am Computer.|The programmer works on the computer.",
    "2|n|der Mechaniker, -|the mechanic (m)|Der Mechaniker repariert das Auto.|The mechanic repairs the car.",
    "2|n|der Koch, -¨e|the cook (m)|Der Koch macht das Essen.|The cook makes the food.",
    "2|n|die Köchin, -nen|the cook (f)|Die Köchin kocht sehr gut.|The cook cooks very well.",
    "2|n|das Land, -¨er|the country|Aus welchem Land kommen Sie?|Which country do you come from?",
    "2|n|die Stadt, -¨e|the city|Ich wohne in einer Stadt.|I live in a city.",
    "2|n|die Sprache, -n|the language|Welche Sprache sprechen Sie?|Which language do you speak?",
    "2|n|die Telefonnummer, -n|the phone number|Wie ist Ihre Telefonnummer?|What is your phone number?",
    "2|n|die Adresse, -n|the address|Wie ist Ihre Adresse?|What is your address?",
    "2|n|die E-Mail, -s|the email|Meine E-Mail ist anna@web.de.|My email is anna@web.de.",
    "2|n|die Straße, -n|the street|Ich wohne in der Hauptstraße.|I live on the main street.",
    "2|n|die Postleitzahl, -en|the postal code|Die Postleitzahl ist 80331.|The postal code is 80331.",
    "2|n|das Alter, -|the age|Wie ist Ihr Alter?|What is your age?",
    "2|n|das Jahr, -e|the year|Ich bin 25 Jahre alt.|I am 25 years old.",
    "2|v|arbeiten|to work|Ich arbeite als Lehrerin.|I work as a teacher.",
    "2|v|wohnen|to live (reside)|Ich wohne in München.|I live in Munich.",
    "2|v|sprechen (spricht)|to speak|Sie spricht drei Sprachen.|She speaks three languages.",
    "2|v|lernen|to learn|Ich lerne Deutsch.|I am learning German.",
    "2|v|studieren|to study (at university)|Er studiert Medizin.|He studies medicine.",
    "2|v|buchstabieren|to spell|Können Sie das buchstabieren?|Can you spell that?",
    "2|p|er|he|Er ist Ingenieur.|He is an engineer.",
    "2|p|sie|she / they|Sie kommt aus Spanien.|She comes from Spain.",
    "2|p|wir|we|Wir wohnen in Berlin.|We live in Berlin.",
    "2|p|woher|from where|Woher kommen Sie?|Where do you come from?",
    "2|p|wo|where|Wo wohnen Sie?|Where do you live?",
    "2|p|was|what|Was sind Sie von Beruf?|What is your profession?",
    "2|a|verheiratet|married|Sind Sie verheiratet?|Are you married?",
    "2|a|ledig|single (unmarried)|Er ist ledig.|He is single.",
    "2|a|geschieden|divorced|Sie ist geschieden.|She is divorced.",
    "3|n|die Familie, -n|the family|Meine Familie ist groß.|My family is big.",
    "3|n|die Eltern (Pl.)|the parents|Meine Eltern wohnen in Köln.|My parents live in Cologne.",
    "3|n|die Mutter, -¨|the mother|Meine Mutter heißt Petra.|My mother's name is Petra.",
    "3|n|der Vater, -¨|the father|Mein Vater ist 50 Jahre alt.|My father is 50 years old.",
    "3|n|die Schwester, -n|the sister|Meine Schwester studiert Kunst.|My sister studies art.",
    "3|n|der Bruder, -¨|the brother|Mein Bruder wohnt in Wien.|My brother lives in Vienna.",
    "3|n|das Kind, -er|the child|Das Kind spielt im Garten.|The child plays in the garden.",
    "3|n|die Tochter, -¨|the daughter|Meine Tochter ist fünf Jahre alt.|My daughter is five years old.",
    "3|n|der Sohn, -¨e|the son|Mein Sohn geht in die Schule.|My son goes to school.",
    "3|n|die Großmutter, -¨|the grandmother|Meine Großmutter kocht sehr gut.|My grandmother cooks very well.",
    "3|n|der Großvater, -¨|the grandfather|Mein Großvater ist 80 Jahre alt.|My grandfather is 80 years old.",
    "3|n|die Großeltern (Pl.)|the grandparents|Meine Großeltern leben auf dem Land.|My grandparents live in the countryside.",
    "3|n|die Geschwister (Pl.)|the siblings|Hast du Geschwister?|Do you have siblings?",
    "3|n|der Mann, -¨er|the man / husband|Mein Mann arbeitet als Arzt.|My husband works as a doctor.",
    "3|n|der Onkel, -|the uncle|Mein Onkel wohnt in Hamburg.|My uncle lives in Hamburg.",
    "3|n|die Tante, -n|the aunt|Meine Tante hat zwei Kinder.|My aunt has two children.",
    "3|n|der Cousin, -s|the cousin (m)|Mein Cousin ist 14 Jahre alt.|My cousin is 14 years old.",
    "3|n|die Cousine, -n|the cousin (f)|Meine Cousine studiert in Berlin.|My cousin studies in Berlin.",
    "3|n|das Baby, -s|the baby|Das Baby schläft.|The baby is sleeping.",
    "3|v|haben (hat)|to have|Ich habe zwei Kinder.|I have two children.",
    "3|v|leben|to live|Wir leben in Deutschland.|We live in Germany.",
    "3|v|spielen|to play|Die Kinder spielen draußen.|The children play outside.",
    "3|a|alt|old|Mein Opa ist sehr alt.|My grandpa is very old.",
    "3|a|jung|young|Die Lehrerin ist jung.|The teacher is young.",
    "3|a|groß|big / tall|Meine Familie ist groß.|My family is big.",
    "3|a|klein|small / short|Das Kind ist noch klein.|The child is still small.",
    "3|p|mein|my|Mein Bruder heißt Tim.|My brother's name is Tim.",
    "3|p|dein|your (informal)|Wie heißt dein Vater?|What is your father's name?",
    "3|p|sein|his|Sein Sohn ist drei Jahre alt.|His son is three years old.",
    "3|p|ihr|her / their|Ihr Mann ist Lehrer.|Her husband is a teacher.",
    "3|p|unser|our|Unser Haus ist groß.|Our house is big.",
    "4|n|das Möbel, -|the piece of furniture|Das Möbel ist neu.|The furniture is new.",
    "4|n|der Tisch, -e|the table|Der Tisch ist aus Holz.|The table is made of wood.",
    "4|n|der Stuhl, -¨e|the chair|Der Stuhl ist bequem.|The chair is comfortable.",
    "4|n|das Sofa, -s|the sofa|Das Sofa ist sehr groß.|The sofa is very big.",
    "4|n|das Bett, -en|the bed|Das Bett ist neu.|The bed is new.",
    "4|n|der Schrank, -¨e|the wardrobe / cabinet|Der Schrank ist braun.|The wardrobe is brown.",
    "4|n|das Regal, -e|the shelf|Das Regal ist voll.|The shelf is full.",
    "4|n|die Lampe, -n|the lamp|Die Lampe ist kaputt.|The lamp is broken.",
    "4|n|der Teppich, -e|the carpet|Der Teppich ist rot.|The carpet is red.",
    "4|n|der Supermarkt, -¨e|the supermarket|Ich gehe in den Supermarkt.|I go to the supermarket.",
    "4|n|das Geschäft, -e|the shop|Das Geschäft ist geschlossen.|The shop is closed.",
    "4|n|der Preis, -e|the price|Wie ist der Preis?|What is the price?",
    "4|n|das Angebot, -e|the offer|Das Angebot ist gut.|The offer is good.",
    "4|n|der Euro, -s|the euro|Das kostet fünf Euro.|That costs five euros.",
    "4|n|der Cent, -s|the cent|Das kostet 99 Cent.|That costs 99 cents.",
    "4|v|kaufen|to buy|Ich kaufe einen Tisch.|I buy a table.",
    "4|v|verkaufen|to sell|Er verkauft sein Auto.|He sells his car.",
    "4|v|kosten|to cost|Was kostet der Stuhl?|What does the chair cost?",
    "4|v|bezahlen|to pay|Ich möchte bezahlen.|I would like to pay.",
    "4|v|brauchen|to need|Ich brauche einen Schrank.|I need a wardrobe.",
    "4|v|suchen|to search / look for|Ich suche eine Lampe.|I am looking for a lamp.",
    "4|v|finden (findet)|to find|Ich finde das Sofa schön.|I find the sofa beautiful.",
    "4|a|billig|cheap|Der Tisch ist billig.|The table is cheap.",
    "4|a|teuer|expensive|Das Sofa ist sehr teuer.|The sofa is very expensive.",
    "4|a|neu|new|Der Schrank ist neu.|The wardrobe is new.",
    "4|a|alt|old (for things)|Der Stuhl ist alt.|The chair is old.",
    "4|a|schön|beautiful / nice|Die Lampe ist schön.|The lamp is nice.",
    "4|a|hässlich|ugly|Der Teppich ist hässlich.|The carpet is ugly.",
    "4|a|modern|modern|Die Möbel sind modern.|The furniture is modern.",
    "4|a|bequem|comfortable|Das Bett ist bequem.|The bed is comfortable.",
    "4|e|Wie viel kostet das?|How much does that cost?|Wie viel kostet das Regal?|How much does the shelf cost?",
    "4|n|die Kasse, -n|the checkout / cash register|Bitte zahlen Sie an der Kasse.|Please pay at the checkout.",
    "5|n|das Ding, -e|the thing|Was ist das für ein Ding?|What kind of thing is that?",
    "5|n|die Brille, -n|the glasses|Meine Brille ist neu.|My glasses are new.",
    "5|n|der Schlüssel, -|the key|Wo ist mein Schlüssel?|Where is my key?",
    "5|n|die Tasche, -n|the bag|Die Tasche ist schwer.|The bag is heavy.",
    "5|n|der Geldbeutel, -|the wallet|Mein Geldbeutel ist weg!|My wallet is gone!",
    "5|n|der Regenschirm, -e|the umbrella|Hast du einen Regenschirm?|Do you have an umbrella?",
    "5|n|die Flasche, -n|the bottle|Die Flasche ist leer.|The bottle is empty.",
    "5|n|das Feuerzeug, -e|the lighter|Hast du ein Feuerzeug?|Do you have a lighter?",
    "5|n|die Uhr, -en|the clock / watch|Die Uhr ist kaputt.|The clock is broken.",
    "5|n|das Handy, -s|the mobile phone|Mein Handy ist neu.|My mobile phone is new.",
    "5|n|die Seife, -n|the soap|Die Seife riecht gut.|The soap smells good.",
    "5|n|das Buch, -¨er|the book|Das Buch ist interessant.|The book is interesting.",
    "5|n|die Zeitung, -en|the newspaper|Ich lese die Zeitung.|I read the newspaper.",
    "5|n|das Foto, -s|the photo|Das Foto ist schön.|The photo is nice.",
    "5|n|die Batterie, -n|the battery|Die Batterie ist leer.|The battery is empty.",
    "5|n|das Produkt, -e|the product|Das Produkt ist gut.|The product is good.",
    "5|n|die Kreditkarte, -n|the credit card|Kann ich mit Kreditkarte bezahlen?|Can I pay by credit card?",
    "5|n|die Dose, -n|the can / tin|Ich kaufe eine Dose Tomaten.|I buy a can of tomatoes.",
    "5|p|dieser|this|Dieser Schlüssel ist meiner.|This key is mine.",
    "5|p|kein|no / not a|Ich habe kein Handy.|I don't have a mobile phone.",
    "5|a|leicht|light / easy|Die Tasche ist leicht.|The bag is light.",
    "5|a|schwer|heavy / difficult|Das Buch ist schwer.|The book is heavy.",
    "5|a|wichtig|important|Der Schlüssel ist wichtig.|The key is important.",
    "5|a|kaputt|broken|Die Uhr ist kaputt.|The watch is broken.",
    "6|n|das Büro, -s|the office|Ich arbeite im Büro.|I work in the office.",
    "6|n|der Computer, -|the computer|Der Computer ist neu.|The computer is new.",
    "6|n|der Drucker, -|the printer|Der Drucker funktioniert nicht.|The printer doesn't work.",
    "6|n|der Bildschirm, -e|the screen / monitor|Der Bildschirm ist groß.|The screen is big.",
    "6|n|die Tastatur, -en|the keyboard|Die Tastatur ist kaputt.|The keyboard is broken.",
    "6|n|die Maus, -¨e|the mouse|Die Maus funktioniert nicht.|The mouse doesn't work.",
    "6|n|das Telefon, -e|the telephone|Das Telefon klingelt.|The telephone is ringing.",
    "6|n|der Kugelschreiber, -|the ballpoint pen|Hast du einen Kugelschreiber?|Do you have a pen?",
    "6|n|der Bleistift, -e|the pencil|Ich schreibe mit Bleistift.|I write with a pencil.",
    "6|n|das Papier, -e|the paper|Ich brauche Papier.|I need paper.",
    "6|n|der Brief, -e|the letter|Ich schreibe einen Brief.|I write a letter.",
    "6|n|die Briefmarke, -n|the stamp|Ich brauche eine Briefmarke.|I need a stamp.",
    "6|n|das Internet, -|the internet|Ich suche im Internet.|I search on the internet.",
    "6|n|das Passwort, -¨er|the password|Wie ist das Passwort?|What is the password?",
    "6|n|die Datei, -en|the file|Die Datei ist groß.|The file is big.",
    "6|n|der Termin, -e|the appointment|Ich habe einen Termin.|I have an appointment.",
    "6|n|die Besprechung, -en|the meeting|Die Besprechung ist um 10 Uhr.|The meeting is at 10 o'clock.",
    "6|v|schreiben|to write|Ich schreibe eine E-Mail.|I write an email.",
    "6|v|lesen (liest)|to read|Er liest einen Brief.|He reads a letter.",
    "6|v|telefonieren|to make a phone call|Ich telefoniere mit meinem Chef.|I am on the phone with my boss.",
    "6|v|drucken|to print|Ich drucke das Dokument.|I print the document.",
    "6|v|funktionieren|to function / work|Der Drucker funktioniert nicht.|The printer doesn't work.",
    "6|v|schicken|to send|Ich schicke eine E-Mail.|I send an email.",
    "6|v|öffnen|to open|Bitte öffnen Sie die Datei.|Please open the file.",
    "6|v|schließen|to close|Bitte schließen Sie die Tür.|Please close the door.",
    "6|n|die Kollegin, -nen|the colleague (f)|Meine Kollegin ist nett.|My colleague is nice.",
    "6|n|der Kollege, -n|the colleague (m)|Mein Kollege hilft mir.|My colleague helps me.",
    "6|n|der Chef, -s|the boss (m)|Der Chef ist im Büro.|The boss is in the office.",
    "7|n|die Freizeit, -|the free time|Was machst du in der Freizeit?|What do you do in your free time?",
    "7|n|das Hobby, -s|the hobby|Mein Hobby ist Musik.|My hobby is music.",
    "7|n|die Musik, -|the music|Ich höre gern Musik.|I like to listen to music.",
    "7|n|der Sport, -|the sport|Ich mache gern Sport.|I like to do sport.",
    "7|n|der Film, -e|the film|Der Film ist toll.|The film is great.",
    "7|n|das Kino, -s|the cinema|Wir gehen ins Kino.|We go to the cinema.",
    "7|n|das Theater, -|the theater|Wir gehen ins Theater.|We go to the theater.",
    "7|n|das Konzert, -e|the concert|Das Konzert ist am Samstag.|The concert is on Saturday.",
    "7|n|das Museum, Museen|the museum|Das Museum ist interessant.|The museum is interesting.",
    "7|n|der Garten, -¨|the garden|Ich arbeite im Garten.|I work in the garden.",
    "7|n|das Fahrrad, -¨er|the bicycle|Ich fahre gern Fahrrad.|I like to ride a bicycle.",
    "7|n|das Schwimmbad, -¨er|the swimming pool|Wir gehen ins Schwimmbad.|We go to the swimming pool.",
    "7|v|schwimmen|to swim|Ich schwimme gern.|I like to swim.",
    "7|v|tanzen|to dance|Sie tanzt sehr gut.|She dances very well.",
    "7|v|singen|to sing|Er singt laut.|He sings loudly.",
    "7|v|kochen|to cook|Ich koche gern italienisch.|I like to cook Italian food.",
    "7|v|fotografieren|to take photos|Ich fotografiere gern.|I like to take photos.",
    "7|v|malen|to paint|Das Kind malt ein Bild.|The child paints a picture.",
    "7|v|wandern|to hike|Wir wandern am Wochenende.|We hike on the weekend.",
    "7|v|hören|to hear / listen|Ich höre Musik.|I listen to music.",
    "7|v|sehen (sieht)|to see / watch|Er sieht einen Film.|He watches a film.",
    "7|a|toll|great|Der Film ist toll!|The film is great!",
    "7|a|langweilig|boring|Das Buch ist langweilig.|The book is boring.",
    "7|a|interessant|interesting|Das Museum ist interessant.|The museum is interesting.",
    "7|a|super|super / great|Das Konzert war super!|The concert was great!",
    "7|a|fantastisch|fantastic|Die Musik ist fantastisch.|The music is fantastic.",
    "7|e|Das ist toll!|That is great!|Du tanzt? Das ist toll!|You dance? That is great!",
    "7|e|Das gefällt mir.|I like that.|Das Bild gefällt mir.|I like the picture.",
    "7|d|gern|gladly / with pleasure|Ich lese gern.|I like to read.",
    "8|n|die Verabredung, -en|the appointment / date|Ich habe eine Verabredung.|I have an appointment.",
    "8|n|das Wochenende, -n|the weekend|Was machst du am Wochenende?|What are you doing on the weekend?",
    "8|n|der Abend, -e|the evening|Am Abend gehe ich ins Kino.|In the evening I go to the cinema.",
    "8|n|der Morgen, -|the morning|Am Morgen trinke ich Kaffee.|In the morning I drink coffee.",
    "8|n|der Mittag, -e|the noon / midday|Am Mittag esse ich in der Kantine.|At noon I eat in the canteen.",
    "8|n|der Nachmittag, -e|the afternoon|Am Nachmittag lerne ich Deutsch.|In the afternoon I learn German.",
    "8|n|die Nacht, -¨e|the night|In der Nacht schlafe ich.|At night I sleep.",
    "8|n|die Zeit, -en|the time|Hast du Zeit?|Do you have time?",
    "8|n|die Idee, -n|the idea|Das ist eine gute Idee!|That is a good idea!",
    "8|v|möchten (möchte)|would like|Ich möchte ins Kino gehen.|I would like to go to the cinema.",
    "8|v|können (kann)|can / to be able to|Kannst du am Samstag?|Can you on Saturday?",
    "8|v|wollen (will)|to want|Willst du mitkommen?|Do you want to come along?",
    "8|v|mitkommen|to come along|Kommst du mit?|Are you coming along?",
    "8|v|treffen (trifft)|to meet|Wir treffen uns um acht.|We meet at eight.",
    "8|v|anfangen (fängt an)|to begin|Der Film fängt um 20 Uhr an.|The film starts at 8 pm.",
    "8|v|aufhören|to stop / end|Der Kurs hört um 17 Uhr auf.|The course ends at 5 pm.",
    "8|e|Hast du Lust?|Do you feel like it?|Hast du Lust auf Kino?|Do you feel like going to the cinema?",
    "8|e|Ja, gern!|Yes, gladly!|Kommst du mit? – Ja, gern!|Are you coming along? – Yes, gladly!",
    "8|e|Leider nicht.|Unfortunately not.|Kannst du kommen? – Leider nicht.|Can you come? – Unfortunately not.",
    "8|e|Tut mir leid.|I'm sorry.|Tut mir leid, ich habe keine Zeit.|I'm sorry, I don't have time.",
    "8|e|Gute Idee!|Good idea!|Wir gehen schwimmen? – Gute Idee!|We go swimming? – Good idea!",
    "8|p|um|at (time)|Wir treffen uns um sieben.|We meet at seven.",
    "8|p|am|on (day/time of day)|Am Montag habe ich einen Kurs.|On Monday I have a course.",
    "8|d|heute|today|Heute gehe ich ins Kino.|Today I go to the cinema.",
    "8|d|morgen|tomorrow|Morgen habe ich frei.|Tomorrow I have off.",
    "8|d|gestern|yesterday|Gestern war ich zu Hause.|Yesterday I was at home.",
    "8|d|jetzt|now|Jetzt habe ich Zeit.|Now I have time.",
    "8|d|dann|then|Dann gehen wir essen.|Then we go eat.",
    "8|d|vielleicht|maybe|Vielleicht komme ich mit.|Maybe I'll come along.",
    "8|d|zusammen|together|Wir kochen zusammen.|We cook together.",
    "9|n|das Essen, -|the food / meal|Das Essen ist lecker.|The food is delicious.",
    "9|n|das Frühstück, -e|the breakfast|Was isst du zum Frühstück?|What do you eat for breakfast?",
    "9|n|das Mittagessen, -|the lunch|Das Mittagessen ist um 12 Uhr.|Lunch is at 12 o'clock.",
    "9|n|das Abendessen, -|the dinner|Was gibt es zum Abendessen?|What's for dinner?",
    "9|n|das Brot, -e|the bread|Ich kaufe Brot.|I buy bread.",
    "9|n|das Brötchen, -|the bread roll|Zum Frühstück esse ich Brötchen.|For breakfast I eat bread rolls.",
    "9|n|die Butter, -|the butter|Ich brauche Butter.|I need butter.",
    "9|n|der Käse, -|the cheese|Der Käse schmeckt gut.|The cheese tastes good.",
    "9|n|die Wurst, -¨e|the sausage|Ich möchte Wurst.|I would like sausage.",
    "9|n|das Fleisch, -|the meat|Ich esse kein Fleisch.|I don't eat meat.",
    "9|n|der Fisch, -e|the fish|Der Fisch ist frisch.|The fish is fresh.",
    "9|n|das Ei, -er|the egg|Zum Frühstück esse ich ein Ei.|For breakfast I eat an egg.",
    "9|n|die Kartoffel, -n|the potato|Ich koche Kartoffeln.|I cook potatoes.",
    "9|n|der Reis, -|the rice|Ich esse gern Reis.|I like to eat rice.",
    "9|n|die Nudel, -n|the noodle / pasta|Die Kinder essen gern Nudeln.|The children like to eat pasta.",
    "9|n|der Salat, -e|the salad|Ich nehme einen Salat.|I'll have a salad.",
    "9|n|die Tomate, -n|the tomato|Die Tomaten sind rot.|The tomatoes are red.",
    "9|n|die Zwiebel, -n|the onion|Ich brauche eine Zwiebel.|I need an onion.",
    "9|n|das Obst, -|the fruit|Obst ist gesund.|Fruit is healthy.",
    "9|n|das Gemüse, -|the vegetables|Ich esse viel Gemüse.|I eat a lot of vegetables.",
    "9|n|der Apfel, -¨|the apple|Der Apfel ist grün.|The apple is green.",
    "9|n|die Banane, -n|the banana|Ich esse eine Banane.|I eat a banana.",
    "9|n|die Orange, -n|the orange|Die Orange ist süß.|The orange is sweet.",
    "9|n|der Kuchen, -|the cake|Der Kuchen schmeckt gut.|The cake tastes good.",
    "9|n|die Schokolade, -n|the chocolate|Ich mag Schokolade.|I like chocolate.",
    "9|n|das Wasser, -|the water|Ich trinke Wasser.|I drink water.",
    "9|n|der Kaffee, -s|the coffee|Möchten Sie einen Kaffee?|Would you like a coffee?",
    "9|n|der Tee, -s|the tea|Ich trinke gern Tee.|I like to drink tea.",
    "9|n|die Milch, -|the milk|Ich nehme Milch im Kaffee.|I take milk in my coffee.",
    "9|n|der Saft, -¨e|the juice|Ich möchte einen Orangensaft.|I would like an orange juice.",
    "9|n|das Bier, -e|the beer|Ein Bier, bitte.|A beer, please.",
    "9|n|der Wein, -e|the wine|Der Wein ist gut.|The wine is good.",
    "9|n|der Zucker, -|the sugar|Ich nehme keinen Zucker.|I don't take sugar.",
    "9|n|das Salz, -e|the salt|Das Essen braucht Salz.|The food needs salt.",
    "9|n|die Einladung, -en|the invitation|Danke für die Einladung!|Thank you for the invitation!",
    "9|n|der Gast, -¨e|the guest|Der Gast kommt um acht.|The guest comes at eight.",
    "9|v|essen (isst)|to eat|Ich esse gern Pizza.|I like to eat pizza.",
    "9|v|trinken|to drink|Er trinkt Kaffee.|He drinks coffee.",
    "9|v|nehmen (nimmt)|to take|Ich nehme den Salat.|I'll take the salad.",
    "9|v|schmecken|to taste|Die Suppe schmeckt gut.|The soup tastes good.",
    "9|v|mögen (mag)|to like|Ich mag Schokolade.|I like chocolate.",
    "9|v|einladen (lädt ein)|to invite|Ich lade dich zum Essen ein.|I invite you for dinner.",
    "9|v|mitbringen|to bring along|Soll ich etwas mitbringen?|Should I bring something?",
    "9|a|lecker|delicious|Das Essen ist lecker!|The food is delicious!",
    "9|a|süß|sweet|Die Schokolade ist süß.|The chocolate is sweet.",
    "9|a|frisch|fresh|Das Brot ist frisch.|The bread is fresh.",
    "9|a|hungrig|hungry|Ich bin hungrig.|I am hungry.",
    "9|a|durstig|thirsty|Ich bin durstig.|I am thirsty.",
    "9|e|Guten Appetit!|Enjoy your meal!|Das Essen ist fertig. Guten Appetit!|The food is ready. Enjoy your meal!",
    "9|e|Zum Wohl!|Cheers!|Zum Wohl! Der Wein ist gut.|Cheers! The wine is good.",
    "10|n|die Reise, -n|the trip / journey|Die Reise war schön.|The trip was nice.",
    "10|n|der Urlaub, -e|the vacation|Ich mache Urlaub in Italien.|I am on vacation in Italy.",
    "10|n|der Flughafen, -¨|the airport|Wir fahren zum Flughafen.|We drive to the airport.",
    "10|n|der Bahnhof, -¨e|the train station|Der Bahnhof ist groß.|The train station is big.",
    "10|n|der Zug, -¨e|the train|Der Zug kommt um 10 Uhr.|The train arrives at 10 o'clock.",
    "10|n|der Bus, -se|the bus|Ich fahre mit dem Bus.|I go by bus.",
    "10|n|die U-Bahn, -en|the subway|Ich nehme die U-Bahn.|I take the subway.",
    "10|n|die Straßenbahn, -en|the tram|Die Straßenbahn fährt zum Bahnhof.|The tram goes to the train station.",
    "10|n|das Flugzeug, -e|the airplane|Das Flugzeug fliegt nach Paris.|The airplane flies to Paris.",
    "10|n|das Auto, -s|the car|Ich fahre mit dem Auto.|I go by car.",
    "10|n|das Taxi, -s|the taxi|Ich nehme ein Taxi.|I take a taxi.",
    "10|n|das Schiff, -e|the ship|Das Schiff ist groß.|The ship is big.",
    "10|n|die Fahrkarte, -n|the ticket (transport)|Ich kaufe eine Fahrkarte.|I buy a ticket.",
    "10|n|der Fahrplan, -¨e|the timetable / schedule|Der Fahrplan hängt an der Wand.|The timetable hangs on the wall.",
    "10|n|die Haltestelle, -n|the stop (bus/tram)|Die Haltestelle ist hier.|The stop is here.",
    "10|n|das Gleis, -e|the platform / track|Der Zug fährt von Gleis 3.|The train departs from platform 3.",
    "10|n|die Abfahrt, -en|the departure|Die Abfahrt ist um 9 Uhr.|The departure is at 9 o'clock.",
    "10|n|die Ankunft, -¨e|the arrival|Die Ankunft ist um 12 Uhr.|The arrival is at 12 o'clock.",
    "10|n|das Hotel, -s|the hotel|Das Hotel ist zentral.|The hotel is central.",
    "10|n|das Gepäck, -|the luggage|Mein Gepäck ist schwer.|My luggage is heavy.",
    "10|n|der Koffer, -|the suitcase|Ich packe meinen Koffer.|I pack my suitcase.",
    "10|v|fahren (fährt)|to drive / go (by vehicle)|Er fährt mit dem Zug.|He goes by train.",
    "10|v|fliegen|to fly|Wir fliegen nach Spanien.|We fly to Spain.",
    "10|v|reisen|to travel|Ich reise gern.|I like to travel.",
    "10|v|ankommen|to arrive|Der Zug kommt um 10 Uhr an.|The train arrives at 10 o'clock.",
    "10|v|abfahren (fährt ab)|to depart|Der Bus fährt um 8 Uhr ab.|The bus departs at 8 o'clock.",
    "10|v|umsteigen|to transfer / change (transport)|Sie müssen in Frankfurt umsteigen.|You have to change in Frankfurt.",
    "10|v|einsteigen|to board / get on|Bitte einsteigen!|Please get on!",
    "10|v|aussteigen|to get off|Ich steige am Bahnhof aus.|I get off at the train station.",
    "10|v|packen|to pack|Ich packe meinen Koffer.|I pack my suitcase.",
    "10|e|Gute Reise!|Have a good trip!|Du fliegst morgen? Gute Reise!|You fly tomorrow? Have a good trip!",
    "10|p|mit|with / by (transport)|Ich fahre mit dem Bus.|I go by bus.",
    "10|p|nach|to (direction/city/country)|Ich fahre nach Berlin.|I go to Berlin.",
    "10|p|von|from|Der Zug fährt von München.|The train departs from Munich.",
    "10|a|schnell|fast|Der Zug ist schnell.|The train is fast.",
    "10|a|langsam|slow|Der Bus ist langsam.|The bus is slow.",
    "10|a|pünktlich|on time / punctual|Der Zug ist pünktlich.|The train is on time.",
    "11|n|der Tag, -e|the day|Der Tag war schön.|The day was nice.",
    "11|n|der Tagesablauf, -¨e|the daily routine|Wie ist dein Tagesablauf?|What is your daily routine?",
    "11|n|die Stunde, -n|the hour|Eine Stunde hat 60 Minuten.|One hour has 60 minutes.",
    "11|n|die Minute, -n|the minute|Warte eine Minute.|Wait a minute.",
    "11|n|die Arbeit, -en|the work|Ich gehe zur Arbeit.|I go to work.",
    "11|n|die Schule, -n|the school|Die Kinder gehen in die Schule.|The children go to school.",
    "11|n|der Kurs, -e|the course|Der Deutschkurs ist um 9 Uhr.|The German course is at 9 o'clock.",
    "11|v|aufstehen|to get up|Ich stehe um 7 Uhr auf.|I get up at 7 o'clock.",
    "11|v|duschen|to shower|Ich dusche am Morgen.|I shower in the morning.",
    "11|v|frühstücken|to have breakfast|Ich frühstücke um 8 Uhr.|I have breakfast at 8 o'clock.",
    "11|v|anfangen (fängt an)|to start / begin|Die Arbeit fängt um 9 Uhr an.|Work starts at 9 o'clock.",
    "11|v|aufhören|to stop / finish|Ich höre um 17 Uhr auf.|I finish at 5 pm.",
    "11|v|einkaufen|to go shopping|Ich kaufe nach der Arbeit ein.|I go shopping after work.",
    "11|v|fernsehen (sieht fern)|to watch TV|Abends sehe ich fern.|In the evening I watch TV.",
    "11|v|schlafen (schläft)|to sleep|Er schläft acht Stunden.|He sleeps eight hours.",
    "11|v|waschen (wäscht)|to wash|Ich wasche mir die Hände.|I wash my hands.",
    "11|v|putzen|to clean|Ich putze die Wohnung.|I clean the apartment.",
    "11|d|früh|early|Ich stehe früh auf.|I get up early.",
    "11|d|spät|late|Es ist schon spät.|It is already late.",
    "11|d|immer|always|Ich frühstücke immer um 8 Uhr.|I always have breakfast at 8.",
    "11|d|oft|often|Ich koche oft am Abend.|I often cook in the evening.",
    "11|d|manchmal|sometimes|Manchmal gehe ich ins Kino.|Sometimes I go to the cinema.",
    "11|d|nie|never|Ich trinke nie Alkohol.|I never drink alcohol.",
    "11|d|zuerst|first|Zuerst dusche ich.|First I shower.",
    "11|d|danach|after that|Danach frühstücke ich.|After that I have breakfast.",
    "11|p|von ... bis|from ... to|Ich arbeite von 9 bis 17 Uhr.|I work from 9 to 5.",
    "11|e|Wie spät ist es?|What time is it?|Wie spät ist es? – Es ist 10 Uhr.|What time is it? – It is 10 o'clock.",
    "12|n|das Fest, -e|the celebration / party|Das Fest war schön.|The celebration was nice.",
    "12|n|die Party, -s|the party|Wir machen eine Party.|We have a party.",
    "12|n|der Geburtstag, -e|the birthday|Mein Geburtstag ist im Mai.|My birthday is in May.",
    "12|n|das Geschenk, -e|the gift / present|Das Geschenk ist für dich.|The gift is for you.",
    "12|n|die Überraschung, -en|the surprise|Das ist eine Überraschung!|That is a surprise!",
    "12|n|die Karte, -n|the card / ticket|Ich schreibe eine Karte.|I write a card.",
    "12|n|die Kerze, -n|the candle|Die Kerzen sind auf dem Kuchen.|The candles are on the cake.",
    "12|n|die Musik, -|the music|Die Musik war laut.|The music was loud.",
    "12|v|feiern|to celebrate|Wir feiern meinen Geburtstag.|We celebrate my birthday.",
    "12|v|schenken|to give (a gift)|Ich schenke ihr Blumen.|I give her flowers.",
    "12|v|gratulieren|to congratulate|Ich gratuliere dir zum Geburtstag!|I congratulate you on your birthday!",
    "12|v|einladen (lädt ein)|to invite|Ich lade meine Freunde ein.|I invite my friends.",
    "12|v|dekorieren|to decorate|Wir dekorieren das Zimmer.|We decorate the room.",
    "12|e|Herzlichen Glückwunsch!|Congratulations! / Happy birthday!|Herzlichen Glückwunsch zum Geburtstag!|Happy birthday!",
    "12|e|Alles Gute!|All the best!|Alles Gute zum Geburtstag!|All the best for your birthday!",
    "12|e|Frohe Weihnachten!|Merry Christmas!|Frohe Weihnachten und ein gutes neues Jahr!|Merry Christmas and a happy new year!",
    "12|e|Frohes neues Jahr!|Happy New Year!|Frohes neues Jahr, liebe Freunde!|Happy New Year, dear friends!",
    "12|d|letztes Jahr|last year|Letztes Jahr war ich in Spanien.|Last year I was in Spain.",
    "12|d|letzte Woche|last week|Letzte Woche hatte ich Geburtstag.|Last week I had my birthday.",
    "12|n|die Blume, -n|the flower|Die Blumen sind schön.|The flowers are beautiful.",
    "12|n|der Ballon, -s|the balloon|Die Ballons sind bunt.|The balloons are colorful.",
    "13|n|der Weg, -e|the way / path|Können Sie mir den Weg zeigen?|Can you show me the way?",
    "13|n|die Kreuzung, -en|the intersection|An der Kreuzung gehen Sie links.|At the intersection go left.",
    "13|n|die Ampel, -n|the traffic light|An der Ampel gehen Sie rechts.|At the traffic light go right.",
    "13|n|die Brücke, -n|the bridge|Gehen Sie über die Brücke.|Go over the bridge.",
    "13|n|die Ecke, -n|the corner|Das Café ist an der Ecke.|The café is at the corner.",
    "13|n|der Platz, -¨e|the square / place|Der Platz ist in der Mitte der Stadt.|The square is in the center of the city.",
    "13|n|der Meter, -|the meter|Es sind 200 Meter.|It is 200 meters.",
    "13|v|gehen (geht)|to go (on foot)|Gehen Sie geradeaus.|Go straight ahead.",
    "13|v|abbiegen|to turn|Biegen Sie links ab.|Turn left.",
    "13|v|zeigen|to show|Können Sie mir das zeigen?|Can you show me that?",
    "13|v|nehmen (nimmt)|to take|Nehmen Sie die zweite Straße links.|Take the second street on the left.",
    "13|d|links|left|Das Museum ist links.|The museum is on the left.",
    "13|d|rechts|right|Die Apotheke ist rechts.|The pharmacy is on the right.",
    "13|d|geradeaus|straight ahead|Gehen Sie geradeaus.|Go straight ahead.",
    "13|d|hier|here|Das Restaurant ist hier.|The restaurant is here.",
    "13|d|dort|there|Die Post ist dort.|The post office is there.",
    "13|d|oben|above / upstairs|Die Wohnung ist oben.|The apartment is upstairs.",
    "13|d|unten|below / downstairs|Das Café ist unten.|The café is downstairs.",
    "13|p|bis zu|up to / until|Gehen Sie bis zur Kreuzung.|Go up to the intersection.",
    "13|p|an ... vorbei|past|Gehen Sie an der Kirche vorbei.|Go past the church.",
    "13|p|gegenüber|opposite|Das Hotel ist gegenüber der Bank.|The hotel is opposite the bank.",
    "13|p|neben|next to|Die Apotheke ist neben der Post.|The pharmacy is next to the post office.",
    "13|p|zwischen|between|Das Café ist zwischen der Bank und der Post.|The café is between the bank and the post office.",
    "13|e|Entschuldigung, wo ist ...?|Excuse me, where is ...?|Entschuldigung, wo ist der Bahnhof?|Excuse me, where is the train station?",
    "13|e|Wie komme ich zum/zur ...?|How do I get to ...?|Wie komme ich zum Bahnhof?|How do I get to the train station?",
    "14|n|die Wohnung, -en|the apartment|Die Wohnung ist groß.|The apartment is big.",
    "14|n|das Haus, -¨er|the house|Das Haus hat einen Garten.|The house has a garden.",
    "14|n|das Zimmer, -|the room|Das Zimmer ist hell.|The room is bright.",
    "14|n|die Küche, -n|the kitchen|Die Küche ist klein.|The kitchen is small.",
    "14|n|das Bad, -¨er|the bathroom|Das Bad ist sauber.|The bathroom is clean.",
    "14|n|das Wohnzimmer, -|the living room|Wir sitzen im Wohnzimmer.|We sit in the living room.",
    "14|n|das Schlafzimmer, -|the bedroom|Das Schlafzimmer ist ruhig.|The bedroom is quiet.",
    "14|n|das Kinderzimmer, -|the children's room|Das Kinderzimmer ist bunt.|The children's room is colorful.",
    "14|n|der Balkon, -e|the balcony|Der Balkon ist sonnig.|The balcony is sunny.",
    "14|n|der Flur, -e|the hallway|Der Flur ist lang.|The hallway is long.",
    "14|n|die Garage, -n|the garage|Das Auto ist in der Garage.|The car is in the garage.",
    "14|n|der Keller, -|the basement|Der Keller ist dunkel.|The basement is dark.",
    "14|n|die Treppe, -n|the stairs|Die Treppe ist steil.|The stairs are steep.",
    "14|n|der Aufzug, -¨e|the elevator|Es gibt einen Aufzug.|There is an elevator.",
    "14|n|die Miete, -n|the rent|Die Miete ist hoch.|The rent is high.",
    "14|n|der Stock, -werke|the floor / story|Ich wohne im dritten Stock.|I live on the third floor.",
    "14|n|das Fenster, -|the window|Das Fenster ist offen.|The window is open.",
    "14|n|die Tür, -en|the door|Die Tür ist geschlossen.|The door is closed.",
    "14|n|die Wand, -¨e|the wall|Das Bild hängt an der Wand.|The picture hangs on the wall.",
    "14|n|der Boden, -¨|the floor|Der Boden ist aus Holz.|The floor is made of wood.",
    "14|n|die Heizung, -en|the heating|Die Heizung ist an.|The heating is on.",
    "14|v|wohnen|to live (reside)|Ich wohne in einer Wohnung.|I live in an apartment.",
    "14|v|umziehen|to move (house)|Wir ziehen nächste Woche um.|We move next week.",
    "14|v|mieten|to rent|Ich miete eine Wohnung.|I rent an apartment.",
    "14|v|einziehen|to move in|Wir ziehen morgen ein.|We move in tomorrow.",
    "14|a|hell|bright|Das Zimmer ist hell.|The room is bright.",
    "14|a|dunkel|dark|Der Keller ist dunkel.|The basement is dark.",
    "14|a|ruhig|quiet|Die Wohnung ist ruhig.|The apartment is quiet.",
    "14|a|laut|loud / noisy|Die Straße ist laut.|The street is noisy.",
    "14|a|gemütlich|cozy|Das Wohnzimmer ist gemütlich.|The living room is cozy.",
    "14|a|sauber|clean|Das Bad ist sauber.|The bathroom is clean.",
    "14|a|schmutzig|dirty|Der Boden ist schmutzig.|The floor is dirty.",
    "14|n|der Quadratmeter, -|the square meter|Die Wohnung hat 80 Quadratmeter.|The apartment has 80 square meters.",
    "15|n|die Apotheke, -n|the pharmacy|Die Apotheke ist in der Hauptstraße.|The pharmacy is on the main street.",
    "15|n|die Bäckerei, -en|the bakery|Ich kaufe Brot in der Bäckerei.|I buy bread at the bakery.",
    "15|n|die Bank, -en|the bank|Die Bank ist gegenüber der Post.|The bank is opposite the post office.",
    "15|n|die Post, -|the post office|Ich gehe zur Post.|I go to the post office.",
    "15|n|das Rathaus, -¨er|the town hall|Das Rathaus ist am Marktplatz.|The town hall is at the market square.",
    "15|n|die Kirche, -n|the church|Die Kirche ist alt.|The church is old.",
    "15|n|das Krankenhaus, -¨er|the hospital|Das Krankenhaus ist groß.|The hospital is big.",
    "15|n|die Bibliothek, -en|the library|Ich lese in der Bibliothek.|I read in the library.",
    "15|n|das Restaurant, -s|the restaurant|Das Restaurant ist gut.|The restaurant is good.",
    "15|n|das Café, -s|the café|Wir treffen uns im Café.|We meet at the café.",
    "15|n|der Markt, -¨e|the market|Am Samstag gehe ich auf den Markt.|On Saturday I go to the market.",
    "15|n|der Park, -s|the park|Der Park ist schön.|The park is nice.",
    "15|n|der Parkplatz, -¨e|the parking lot|Der Parkplatz ist voll.|The parking lot is full.",
    "15|n|die Polizei, -|the police|Die Polizei ist da.|The police are there.",
    "15|n|die Tankstelle, -n|the gas station|Die Tankstelle ist an der Ecke.|The gas station is at the corner.",
    "15|n|das Zentrum, Zentren|the center|Das Hotel ist im Zentrum.|The hotel is in the center.",
    "15|n|die Metzgerei, -en|the butcher shop|Ich kaufe Fleisch in der Metzgerei.|I buy meat at the butcher shop.",
    "15|v|besuchen|to visit|Ich besuche das Museum.|I visit the museum.",
    "15|a|zentral|central|Die Wohnung ist zentral.|The apartment is central.",
    "15|p|in|in|Ich bin in der Stadt.|I am in the city.",
    "15|p|auf|on / at|Ich gehe auf den Markt.|I go to the market.",
    "15|p|vor|in front of|Ich warte vor der Bank.|I wait in front of the bank.",
    "15|p|hinter|behind|Der Parkplatz ist hinter dem Haus.|The parking lot is behind the house.",
    "16|n|der Termin, -e|the appointment|Ich habe einen Termin beim Arzt.|I have an appointment at the doctor's.",
    "16|n|der Kalender, -|the calendar|Ich schreibe den Termin in den Kalender.|I write the appointment in the calendar.",
    "16|n|die Woche, -n|the week|Die Woche hat sieben Tage.|The week has seven days.",
    "16|n|der Montag, -e|Monday|Am Montag habe ich einen Kurs.|On Monday I have a course.",
    "16|n|der Dienstag, -e|Tuesday|Am Dienstag gehe ich schwimmen.|On Tuesday I go swimming.",
    "16|n|der Mittwoch, -e|Wednesday|Am Mittwoch arbeite ich nicht.|On Wednesday I don't work.",
    "16|n|der Donnerstag, -e|Thursday|Am Donnerstag treffe ich Freunde.|On Thursday I meet friends.",
    "16|n|der Freitag, -e|Friday|Am Freitag gehen wir essen.|On Friday we go out to eat.",
    "16|n|der Samstag, -e|Saturday|Am Samstag kaufe ich ein.|On Saturday I go shopping.",
    "16|n|der Sonntag, -e|Sunday|Am Sonntag schlafe ich lange.|On Sunday I sleep in.",
    "16|n|der Monat, -e|the month|Welcher Monat ist jetzt?|Which month is it now?",
    "16|n|der Januar, -e|January|Im Januar ist es kalt.|In January it is cold.",
    "16|n|der Februar, -e|February|Im Februar ist Karneval.|In February is carnival.",
    "16|n|der März, -e|March|Im März wird es wärmer.|In March it gets warmer.",
    "16|n|der April, -e|April|Im April regnet es oft.|In April it often rains.",
    "16|n|der Mai, -e|May|Im Mai blühen die Blumen.|In May the flowers bloom.",
    "16|n|der Juni, -s|June|Im Juni beginnt der Sommer.|In June summer begins.",
    "16|n|der Juli, -s|July|Im Juli habe ich Urlaub.|In July I have vacation.",
    "16|n|der August, -e|August|Im August ist es heiß.|In August it is hot.",
    "16|n|der September, -|September|Im September beginnt die Schule.|In September school begins.",
    "16|n|der Oktober, -|October|Im Oktober ist Oktoberfest.|In October is Oktoberfest.",
    "16|n|der November, -|November|Im November ist es dunkel.|In November it is dark.",
    "16|n|der Dezember, -|December|Im Dezember ist Weihnachten.|In December is Christmas.",
    "16|v|absagen|to cancel|Ich muss den Termin absagen.|I have to cancel the appointment.",
    "16|v|verschieben|to postpone|Können wir den Termin verschieben?|Can we postpone the appointment?",
    "16|v|vereinbaren|to arrange / make (appointment)|Ich möchte einen Termin vereinbaren.|I would like to make an appointment.",
    "16|e|Welcher Tag ist heute?|What day is today?|Welcher Tag ist heute? – Heute ist Montag.|What day is today? – Today is Monday.",
    "16|e|Wann haben Sie Zeit?|When do you have time?|Wann haben Sie Zeit? – Am Dienstag.|When do you have time? – On Tuesday.",
    "16|p|im|in (month/season)|Im Sommer fahre ich ans Meer.|In summer I go to the sea.",
    "17|n|der Plan, -¨e|the plan|Was ist dein Plan für morgen?|What is your plan for tomorrow?",
    "17|n|der Wunsch, -¨e|the wish|Mein Wunsch ist eine Reise.|My wish is a trip.",
    "17|n|der Traum, -¨e|the dream|Mein Traum ist ein Haus am Meer.|My dream is a house by the sea.",
    "17|n|die Zukunft, -|the future|In der Zukunft möchte ich reisen.|In the future I would like to travel.",
    "17|v|möchten (möchte)|would like|Ich möchte Deutsch lernen.|I would like to learn German.",
    "17|v|werden (wird)|to become / will|Ich werde Lehrer.|I will become a teacher.",
    "17|v|planen|to plan|Wir planen eine Reise.|We plan a trip.",
    "17|v|hoffen|to hope|Ich hoffe, das Wetter ist gut.|I hope the weather is good.",
    "17|v|wünschen|to wish|Ich wünsche mir ein Fahrrad.|I wish for a bicycle.",
    "17|v|müssen (muss)|must / have to|Ich muss morgen arbeiten.|I have to work tomorrow.",
    "17|v|sollen (soll)|should / shall|Soll ich dir helfen?|Should I help you?",
    "17|v|dürfen (darf)|may / to be allowed to|Darf ich hier rauchen?|May I smoke here?",
    "17|d|bald|soon|Ich komme bald.|I am coming soon.",
    "17|d|später|later|Bis später!|See you later!",
    "17|d|nächste Woche|next week|Nächste Woche fahre ich nach Hamburg.|Next week I go to Hamburg.",
    "17|d|nächstes Jahr|next year|Nächstes Jahr lerne ich Spanisch.|Next year I learn Spanish.",
    "17|e|Ich möchte gern ...|I would like to ...|Ich möchte gern nach Italien reisen.|I would like to travel to Italy.",
    "17|a|wichtig|important|Der Termin ist wichtig.|The appointment is important.",
    "17|a|möglich|possible|Ist das möglich?|Is that possible?",
    "18|n|die Gesundheit, -|the health|Gesundheit ist wichtig.|Health is important.",
    "18|n|die Krankheit, -en|the illness|Er hat eine Krankheit.|He has an illness.",
    "18|n|der Arzt, -¨e|the doctor (m)|Ich gehe zum Arzt.|I go to the doctor.",
    "18|n|der Schmerz, -en|the pain|Ich habe Schmerzen.|I have pain.",
    "18|n|der Kopf, -¨e|the head|Mein Kopf tut weh.|My head hurts.",
    "18|n|die Kopfschmerzen (Pl.)|the headache|Ich habe Kopfschmerzen.|I have a headache.",
    "18|n|der Bauch, -¨e|the belly / stomach|Mein Bauch tut weh.|My stomach hurts.",
    "18|n|die Bauchschmerzen (Pl.)|the stomachache|Er hat Bauchschmerzen.|He has a stomachache.",
    "18|n|der Rücken, -|the back|Mein Rücken tut weh.|My back hurts.",
    "18|n|das Fieber, -|the fever|Sie hat Fieber.|She has a fever.",
    "18|n|der Husten, -|the cough|Ich habe Husten.|I have a cough.",
    "18|n|der Schnupfen, -|the cold (runny nose)|Ich habe Schnupfen.|I have a runny nose.",
    "18|n|die Erkältung, -en|the cold (illness)|Ich habe eine Erkältung.|I have a cold.",
    "18|n|das Medikament, -e|the medicine|Nehmen Sie dieses Medikament.|Take this medicine.",
    "18|n|die Tablette, -n|the pill / tablet|Nehmen Sie dreimal täglich eine Tablette.|Take a tablet three times a day.",
    "18|n|das Rezept, -e|the prescription / recipe|Der Arzt schreibt ein Rezept.|The doctor writes a prescription.",
    "18|n|der Arm, -e|the arm|Mein Arm tut weh.|My arm hurts.",
    "18|n|das Bein, -e|the leg|Mein Bein ist gebrochen.|My leg is broken.",
    "18|n|die Hand, -¨e|the hand|Gib mir deine Hand.|Give me your hand.",
    "18|n|der Fuß, -¨e|the foot|Mein Fuß tut weh.|My foot hurts.",
    "18|n|das Auge, -n|the eye|Ihre Augen sind blau.|Her eyes are blue.",
    "18|n|das Ohr, -en|the ear|Meine Ohren tun weh.|My ears hurt.",
    "18|n|die Nase, -n|the nose|Meine Nase ist verstopft.|My nose is blocked.",
    "18|n|der Mund, -¨er|the mouth|Öffnen Sie den Mund.|Open your mouth.",
    "18|n|der Zahn, -¨e|the tooth|Mein Zahn tut weh.|My tooth hurts.",
    "18|n|der Hals, -¨e|the throat / neck|Ich habe Halsschmerzen.|I have a sore throat.",
    "18|n|der Finger, -|the finger|Ich habe mir in den Finger geschnitten.|I cut my finger.",
    "18|v|wehtun|to hurt|Der Kopf tut weh.|The head hurts.",
    "18|v|sich fühlen|to feel (oneself)|Ich fühle mich schlecht.|I feel bad.",
    "18|e|Gute Besserung!|Get well soon!|Du bist krank? Gute Besserung!|You are sick? Get well soon!",
    "18|e|Was fehlt Ihnen?|What's wrong with you? (formal)|Was fehlt Ihnen? – Ich habe Kopfschmerzen.|What's wrong? – I have a headache.",
    "18|a|krank|sick / ill|Ich bin krank.|I am sick.",
    "18|a|gesund|healthy|Er ist wieder gesund.|He is healthy again.",
    "18|a|müde|tired|Ich bin sehr müde.|I am very tired.",
    "18|a|fit|fit|Ich fühle mich fit.|I feel fit.",
    "19|n|das Aussehen, -|the appearance|Sein Aussehen ist modern.|His appearance is modern.",
    "19|n|das Haar, -e|the hair|Sie hat blonde Haare.|She has blonde hair.",
    "19|n|das Gesicht, -er|the face|Er hat ein rundes Gesicht.|He has a round face.",
    "19|n|der Bart, -¨e|the beard|Er hat einen Bart.|He has a beard.",
    "19|n|der Charakter, -e|the character|Er hat einen guten Charakter.|He has a good character.",
    "19|a|blond|blond|Sie ist blond.|She is blond.",
    "19|a|dunkel|dark|Er hat dunkle Haare.|He has dark hair.",
    "19|a|lang|long|Ihre Haare sind lang.|Her hair is long.",
    "19|a|kurz|short|Er hat kurze Haare.|He has short hair.",
    "19|a|dick|fat / thick|Das Buch ist dick.|The book is thick.",
    "19|a|dünn|thin|Sie ist sehr dünn.|She is very thin.",
    "19|a|schlank|slim|Die Frau ist schlank.|The woman is slim.",
    "19|a|hübsch|pretty|Sie ist sehr hübsch.|She is very pretty.",
    "19|a|nett|nice|Er ist sehr nett.|He is very nice.",
    "19|a|freundlich|friendly|Die Nachbarin ist freundlich.|The neighbor is friendly.",
    "19|a|unfreundlich|unfriendly|Der Kellner ist unfreundlich.|The waiter is unfriendly.",
    "19|a|lustig|funny|Er ist sehr lustig.|He is very funny.",
    "19|a|traurig|sad|Sie ist traurig.|She is sad.",
    "19|a|ruhig|calm / quiet|Er ist ein ruhiger Mensch.|He is a calm person.",
    "19|a|nervös|nervous|Ich bin nervös.|I am nervous.",
    "19|a|intelligent|intelligent|Sie ist sehr intelligent.|She is very intelligent.",
    "19|a|fleißig|hardworking / diligent|Er ist sehr fleißig.|He is very hardworking.",
    "19|a|faul|lazy|Die Katze ist faul.|The cat is lazy.",
    "19|a|sympathisch|likeable / nice|Er ist sympathisch.|He is likeable.",
    "19|v|aussehen (sieht aus)|to look (appear)|Sie sieht gut aus.|She looks good.",
    "19|v|tragen (trägt)|to wear / carry|Er trägt eine Brille.|He wears glasses.",
    "20|n|der Haushalt, -e|the household|Ich mache den Haushalt.|I do the housework.",
    "20|n|die Waschmaschine, -n|the washing machine|Die Waschmaschine ist kaputt.|The washing machine is broken.",
    "20|n|der Kühlschrank, -¨e|the refrigerator|Der Kühlschrank ist leer.|The refrigerator is empty.",
    "20|n|der Herd, -e|the stove|Der Herd ist neu.|The stove is new.",
    "20|n|die Spülmaschine, -n|the dishwasher|Wir haben eine Spülmaschine.|We have a dishwasher.",
    "20|n|der Staubsauger, -|the vacuum cleaner|Wo ist der Staubsauger?|Where is the vacuum cleaner?",
    "20|n|das Geschirr, -e|the dishes|Ich spüle das Geschirr.|I wash the dishes.",
    "20|n|der Müll, -|the trash / garbage|Ich bringe den Müll raus.|I take the trash out.",
    "20|n|die Wäsche, -|the laundry|Ich wasche die Wäsche.|I do the laundry.",
    "20|n|der Besen, -|the broom|Der Besen steht in der Ecke.|The broom is in the corner.",
    "20|n|das Handtuch, -¨er|the towel|Ich brauche ein Handtuch.|I need a towel.",
    "20|n|der Teller, -|the plate|Der Teller ist auf dem Tisch.|The plate is on the table.",
    "20|n|die Tasse, -n|the cup|Die Tasse ist heiß.|The cup is hot.",
    "20|n|das Glas, -¨er|the glass|Ein Glas Wasser, bitte.|A glass of water, please.",
    "20|n|das Messer, -|the knife|Das Messer ist scharf.|The knife is sharp.",
    "20|n|die Gabel, -n|the fork|Wo ist die Gabel?|Where is the fork?",
    "20|n|der Löffel, -|the spoon|Ich brauche einen Löffel.|I need a spoon.",
    "20|n|der Topf, -¨e|the pot|Das Wasser ist im Topf.|The water is in the pot.",
    "20|n|die Pfanne, -n|the pan|Ich brate Eier in der Pfanne.|I fry eggs in the pan.",
    "20|v|spülen|to wash (dishes)|Ich spüle das Geschirr.|I wash the dishes.",
    "20|v|aufräumen|to tidy up|Ich räume das Zimmer auf.|I tidy up the room.",
    "20|v|staubsaugen|to vacuum|Ich staubsauge den Teppich.|I vacuum the carpet.",
    "20|v|bügeln|to iron|Ich bügle die Hemden.|I iron the shirts.",
    "20|v|abwaschen (wäscht ab)|to wash up|Ich wasche heute ab.|I wash up today.",
    "20|v|wegwerfen (wirft weg)|to throw away|Wirf den Müll weg!|Throw away the trash!",
    "21|n|die Regel, -n|the rule|Was sind die Regeln?|What are the rules?",
    "21|n|das Verbot, -e|the prohibition|Hier ist ein Rauchverbot.|There is a smoking ban here.",
    "21|n|die Erlaubnis, -se|the permission|Ich brauche eine Erlaubnis.|I need permission.",
    "21|n|die Ordnung, -en|the order|Ordnung ist wichtig.|Order is important.",
    "21|n|das Schild, -er|the sign|Das Schild sagt: Rauchen verboten.|The sign says: No smoking.",
    "21|v|müssen (muss)|must / have to|Man muss hier leise sein.|One has to be quiet here.",
    "21|v|dürfen (darf)|may / to be allowed|Hier darf man nicht rauchen.|One may not smoke here.",
    "21|v|sollen (soll)|should|Du sollst nicht so laut sein.|You should not be so loud.",
    "21|v|erlauben|to allow|Meine Eltern erlauben das nicht.|My parents don't allow that.",
    "21|v|verbieten|to forbid|Rauchen ist hier verboten.|Smoking is forbidden here.",
    "21|a|verboten|forbidden|Parken ist hier verboten.|Parking is forbidden here.",
    "21|a|erlaubt|allowed|Hunde sind hier erlaubt.|Dogs are allowed here.",
    "21|a|leise|quiet / soft|Bitte sei leise!|Please be quiet!",
    "21|a|laut|loud|Die Musik ist zu laut.|The music is too loud.",
    "21|e|Man darf hier nicht ...|You are not allowed to ... here.|Man darf hier nicht rauchen.|You are not allowed to smoke here.",
    "21|e|Man muss ...|One has to ...|Man muss die Regeln beachten.|One has to follow the rules.",
    "21|p|man|one / you (impersonal)|Man muss pünktlich sein.|One has to be on time.",
    "22|n|die Kleidung, -|the clothing|Die Kleidung ist modern.|The clothing is modern.",
    "22|n|das Hemd, -en|the shirt|Das Hemd ist weiß.|The shirt is white.",
    "22|n|die Hose, -n|the pants / trousers|Die Hose ist blau.|The pants are blue.",
    "22|n|die Jeans, -|the jeans|Die Jeans ist neu.|The jeans are new.",
    "22|n|der Rock, -¨e|the skirt|Der Rock ist kurz.|The skirt is short.",
    "22|n|das Kleid, -er|the dress|Das Kleid ist schön.|The dress is beautiful.",
    "22|n|der Pullover, -|the sweater / pullover|Der Pullover ist warm.|The sweater is warm.",
    "22|n|die Jacke, -n|the jacket|Die Jacke ist rot.|The jacket is red.",
    "22|n|der Mantel, -¨|the coat|Der Mantel ist lang.|The coat is long.",
    "22|n|das T-Shirt, -s|the T-shirt|Das T-Shirt ist blau.|The T-shirt is blue.",
    "22|n|die Bluse, -n|the blouse|Die Bluse ist elegant.|The blouse is elegant.",
    "22|n|der Anzug, -¨e|the suit|Er trägt einen Anzug.|He wears a suit.",
    "22|n|die Mütze, -n|the cap / hat|Die Mütze ist warm.|The cap is warm.",
    "22|n|der Hut, -¨e|the hat|Er trägt einen Hut.|He wears a hat.",
    "22|n|der Schuh, -e|the shoe|Die Schuhe sind bequem.|The shoes are comfortable.",
    "22|n|der Stiefel, -|the boot|Die Stiefel sind aus Leder.|The boots are made of leather.",
    "22|n|die Socke, -n|the sock|Die Socken sind rot.|The socks are red.",
    "22|n|der Schal, -s|the scarf|Der Schal ist weich.|The scarf is soft.",
    "22|n|die Handschuhe (Pl.)|the gloves|Ich brauche Handschuhe.|I need gloves.",
    "22|n|die Größe, -n|the size|Welche Größe haben Sie?|What size do you have?",
    "22|v|anziehen|to put on (clothing)|Ich ziehe die Jacke an.|I put on the jacket.",
    "22|v|ausziehen|to take off (clothing)|Zieh die Schuhe aus!|Take off the shoes!",
    "22|v|tragen (trägt)|to wear|Sie trägt ein Kleid.|She wears a dress.",
    "22|v|anprobieren|to try on|Kann ich das anprobieren?|Can I try that on?",
    "22|v|passen|to fit|Die Hose passt nicht.|The pants don't fit.",
    "22|v|stehen|to suit|Das Kleid steht dir gut.|The dress suits you well.",
    "22|a|eng|tight|Die Hose ist zu eng.|The pants are too tight.",
    "22|a|weit|wide / loose|Das T-Shirt ist zu weit.|The T-shirt is too loose.",
    "22|a|elegant|elegant|Der Anzug ist elegant.|The suit is elegant.",
    "22|e|Das steht dir gut!|That suits you!|Das Kleid steht dir gut!|The dress suits you!",
    "22|n|die Farbe, -n|the color|Welche Farbe magst du?|Which color do you like?",
    "22|a|rot|red|Die Jacke ist rot.|The jacket is red.",
    "22|a|blau|blue|Der Himmel ist blau.|The sky is blue.",
    "22|a|grün|green|Das Gras ist grün.|The grass is green.",
    "22|a|gelb|yellow|Die Banane ist gelb.|The banana is yellow.",
    "22|a|weiß|white|Das Hemd ist weiß.|The shirt is white.",
    "22|a|schwarz|black|Die Schuhe sind schwarz.|The shoes are black.",
    "22|a|braun|brown|Der Mantel ist braun.|The coat is brown.",
    "22|a|grau|gray|Der Pullover ist grau.|The sweater is gray.",
    "23|n|das Wetter, -|the weather|Wie ist das Wetter?|How is the weather?",
    "23|n|die Sonne, -n|the sun|Die Sonne scheint.|The sun is shining.",
    "23|n|der Regen, -|the rain|Es gibt viel Regen.|There is a lot of rain.",
    "23|n|der Schnee, -|the snow|Im Winter gibt es Schnee.|In winter there is snow.",
    "23|n|der Wind, -e|the wind|Der Wind ist stark.|The wind is strong.",
    "23|n|die Wolke, -n|the cloud|Es gibt viele Wolken.|There are many clouds.",
    "23|n|das Gewitter, -|the thunderstorm|Es gibt ein Gewitter.|There is a thunderstorm.",
    "23|n|der Nebel, -|the fog|Am Morgen gibt es Nebel.|In the morning there is fog.",
    "23|n|die Temperatur, -en|the temperature|Die Temperatur ist 20 Grad.|The temperature is 20 degrees.",
    "23|n|der Grad, -e|the degree|Es sind 30 Grad.|It is 30 degrees.",
    "23|n|der Frühling, -e|the spring|Im Frühling blühen die Blumen.|In spring the flowers bloom.",
    "23|n|der Sommer, -|the summer|Im Sommer ist es heiß.|In summer it is hot.",
    "23|n|der Herbst, -e|the autumn / fall|Im Herbst fallen die Blätter.|In autumn the leaves fall.",
    "23|n|der Winter, -|the winter|Im Winter ist es kalt.|In winter it is cold.",
    "23|n|die Jahreszeit, -en|the season|Welche Jahreszeit magst du?|Which season do you like?",
    "23|n|der Himmel, -|the sky|Der Himmel ist blau.|The sky is blue.",
    "23|v|regnen|to rain|Es regnet.|It is raining.",
    "23|v|schneien|to snow|Es schneit.|It is snowing.",
    "23|v|scheinen|to shine|Die Sonne scheint.|The sun is shining.",
    "23|a|kalt|cold|Im Winter ist es kalt.|In winter it is cold.",
    "23|a|warm|warm|Im Frühling ist es warm.|In spring it is warm.",
    "23|a|heiß|hot|Im Sommer ist es heiß.|In summer it is hot.",
    "23|a|kühl|cool|Am Abend ist es kühl.|In the evening it is cool.",
    "23|a|sonnig|sunny|Heute ist es sonnig.|Today it is sunny.",
    "23|a|bewölkt|cloudy|Morgen ist es bewölkt.|Tomorrow it is cloudy.",
    "23|a|windig|windy|Es ist sehr windig.|It is very windy.",
    "23|a|neblig|foggy|Am Morgen ist es neblig.|In the morning it is foggy.",
    "23|a|trocken|dry|Im Sommer ist es trocken.|In summer it is dry.",
    "23|a|nass|wet|Die Straße ist nass.|The street is wet.",
    "23|e|Wie ist das Wetter?|How is the weather?|Wie ist das Wetter heute?|How is the weather today?",
    "23|e|Es ist schönes Wetter.|The weather is nice.|Es ist schönes Wetter, wir gehen spazieren.|The weather is nice, we go for a walk.",
    "24|n|das Fest, -e|the celebration / festival|Das Fest ist am Samstag.|The festival is on Saturday.",
    "24|n|die Feier, -n|the celebration / party|Die Feier war schön.|The celebration was nice.",
    "24|n|Weihnachten, -|Christmas|Weihnachten ist im Dezember.|Christmas is in December.",
    "24|n|der Weihnachtsbaum, -¨e|the Christmas tree|Wir schmücken den Weihnachtsbaum.|We decorate the Christmas tree.",
    "24|n|Ostern, -|Easter|Ostern ist im Frühling.|Easter is in spring.",
    "24|n|Silvester, -|New Year's Eve|An Silvester machen wir eine Party.|On New Year's Eve we have a party.",
    "24|n|die Hochzeit, -en|the wedding|Die Hochzeit ist im Juni.|The wedding is in June.",
    "24|n|der Feiertag, -e|the holiday / public holiday|Morgen ist ein Feiertag.|Tomorrow is a public holiday.",
    "24|n|der Karneval, -e|the carnival|Karneval ist im Februar.|Carnival is in February.",
    "24|n|der Valentinstag, -e|Valentine's Day|Am Valentinstag schenke ich Blumen.|On Valentine's Day I give flowers.",
    "24|n|der Muttertag, -e|Mother's Day|Am Muttertag besuche ich meine Mutter.|On Mother's Day I visit my mother.",
    "24|n|das Neujahr, -e|New Year|Frohes Neujahr!|Happy New Year!",
    "24|n|die Tradition, -en|the tradition|Das ist eine alte Tradition.|That is an old tradition.",
    "24|n|der Brauch, -¨e|the custom|Das ist ein deutscher Brauch.|That is a German custom.",
    "24|n|das Feuerwerk, -e|the fireworks|An Silvester gibt es Feuerwerk.|On New Year's Eve there are fireworks.",
    "24|v|feiern|to celebrate|Wir feiern Weihnachten zusammen.|We celebrate Christmas together.",
    "24|v|schmücken|to decorate|Wir schmücken das Haus.|We decorate the house.",
    "24|v|schenken|to give (as a gift)|Was schenkst du ihr?|What do you give her?",
    "24|v|wünschen|to wish|Ich wünsche dir frohe Weihnachten.|I wish you a merry Christmas.",
    "24|v|singen|to sing|Wir singen Weihnachtslieder.|We sing Christmas songs.",
    "24|e|Frohe Ostern!|Happy Easter!|Frohe Ostern! Hier ist ein Ei für dich.|Happy Easter! Here is an egg for you.",
    "24|e|Schöne Feiertage!|Happy holidays!|Schöne Feiertage und guten Rutsch!|Happy holidays and happy New Year!",
    "24|e|Alles Gute zum Geburtstag!|Happy birthday!|Alles Gute zum Geburtstag, liebe Maria!|Happy birthday, dear Maria!",
    "24|a|festlich|festive|Das Essen ist festlich.|The food is festive.",
    "24|a|fröhlich|cheerful / merry|Die Kinder sind fröhlich.|The children are cheerful.",
    "24|n|das Lied, -er|the song|Das Lied ist schön.|The song is beautiful.",
    "24|n|das Weihnachtslied, -er|the Christmas carol|Wir singen ein Weihnachtslied.|We sing a Christmas carol."

];

// 🔧 Parser: Converts raw strings to engine-ready objects
function parseRawData(rawArray) {
    const units = {};
    rawArray.forEach((line, index) => {
        if (!line || line.trim() === '') return;
        const [u, type, de, en, deEx, enEx] = line.split('|').map(s => (s || '').trim());
        const unitNum = parseInt(u);
        if (isNaN(unitNum)) return;

        if (!units[unitNum]) units[unitNum] = [];
        units[unitNum].push({
            id: index,
            de: de,
            en: en,
            type: type || 'Vocab',
            context: deEx || '' // TTS & UI will handle cleaning/display
        });
    });

    // Convert map to sequential array [Unit 1, Unit 2, ...]
    const maxUnit = Math.max(...Object.keys(units).map(Number), 24);
    const result = [];
    for (let i = 1; i <= maxUnit; i++) {
        result.push(units[i] || []);
    }
    return result;
}

export const levelConfig = {
    appId: 'german-a1-app',
    levelTitle: '📚 A1 German',
    levelSubtitle: 'Massive Vocabulary Set',
    progressLabel: 'Overall Progress',
    sectionLabel: 'Unit',
    sectionLabels: [
        'Begrüßungen', 'Zahlen & Farben', 'Familie', 'Wohnen', 'Essen & Trinken',
        'Kleidung', 'Körper & Gesundheit', 'Tagesablauf', 'Freizeit', 'Reisen',
        'Einkaufen', 'Restaurant', 'Wetter', 'Jahreszeiten', 'Berufe',
        'Schule & Lernen', 'Technik', 'Stadt & Verkehr', 'Natur', 'Feste',
        'Gefühle', 'Kommunikation', 'Grammatik Basics', 'Review & Practice'
    ],
    typeFilters: [
        { value: 'all', label: '🔍 All Word Types' },
        { value: 'v', label: '🏃‍♂️ Verbs only' },
        { value: 'n', label: '📦 Nouns only' },
        { value: 'a', label: '✨ Adjectives only' },
        { value: 'd', label: '🕒 Adverbs only' },
        { value: 'e', label: '💬 Expressions only' },
        { value: 'p', label: '🔗 Pronouns/Preps' }
    ],
    vocabulary: parseRawData(RAW_A1_DATA),
    parseRules: { format: 'standard' },
    uiOverrides: {}
};